name: ai4beg
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib=3.9
  - numpy=1.26
  - requests=2.32
  - scikit-learn
  - scipy=1.13
  - opencv
  - setuptools
  - pytorch
  - torchtext
  - torchvision
  - torchdata
  - pip
  - pip:
      - gensim==4.3.3 
      - gym==0.26.2
      - huggingface==0.0.1
      - imageio==2.35.0
      - keras==3.5.0
      - nltk==3.8.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pygame==2.6.0
      - scikit-image==0.24.0
      - seaborn==0.13.2
      - smart-open==7.0.4
      - tensorboard-data-server==0.7.2
      - tensorflow-datasets==4.9.3  # downgraded for Python 3.9 compatibility
      - tensorflow-hub==0.16.1
      - tensorflow==2.17.0
      - tensorboard==2.17.1
      - tokenizers==0.20.0
      - torchinfo==1.8.0
      - tqdm==4.66.5
